export const allVar: any = {
    width: null,
    height: null,
    paddleW: null,
    paddleH: null,
    leftPaddleX: null,
    rightPaddleX: null,
    leftPaddleY: null,
    rightPaddleY: null,
    ballSize: null,
    ballX: null,
    ballY: null,
    ballRadius: null,
    ballVelocity: null,
    ballSpeed: null,
    nameLeftPlayer: null,
    nameRightPlayer: null,
    scoreLimit: null,
    scoreLeftPlayer: null,
    scoreRightPlayer: null,
    winnerId: null,
    loserId: null,
    key: null,
    gameStatus: null,
    gameId: null,
    gameMap: null,
    gameMode: null,
    isFinished: null,
    hasLeft: null,
    ballDirection: { x: 0, y: 0 },
};

